version: 1.0.{build}

deploy:
  provider: NuGet
  server: https://www.myget.org/F/obsidian/api/v3/index.json
  api_key:
    secure: Q9v7Huzgx+vJC3E8oGhw/mART6brch/Dg+OIJLCo2YCdexCBCMb0/8Nay/Ldq07o
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*(\.|\.s)nupkg/
  
before_build:
    - cmd: nuget restore
    
init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion-beta-$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(buildVersion)'
  version_prefix: '$(buildVersion)'
  package_version: '$(buildVersion)'
  assembly_version: '$(buildVersion)'
  file_version: '$(buildVersion)'
  informational_version: '$(nugetVersion)'

configuration: Release

build:
  verbosity: minimal

test: off