deploy:
  provider: NuGet
  server: https://www.myget.org/F/obsidian/api/v3/index.json
  api_key:
    secure: Q9v7Huzgx+vJC3E8oGhw/mART6brch/Dg+OIJLCo2YCdexCBCMb0/8Nay/Ldq07o
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*(\.|\.s)nupkg/
before_build:
    - cmd: nuget restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}.${env:APPVEYOR_BUILD_VERSION}'