before_build:
    - cmd: nuget restore

build:
  verbosity: minimal

test: off

artifacts:
- path: '**\*.nupkg'
  name: nupkg


deploy:
- provider: NuGet
  server: https://www.myget.org/F/obsidian/api/v2/package
  api_key:
    secure: Q9v7Huzgx+vJC3E8oGhw/mART6brch/Dg+OIJLCo2YCdexCBCMb0/8Nay/Ldq07o
  skip_symbols: false
  symbol_server: https://www.myget.org/F/obsidian/api/v3/index.json
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: master