before_build:
    - cmd: nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  verbosity: minimal

test: off

deploy:
- provider: NuGet
  server: https://www.myget.org/F/obsidian/api/v3/index.json
  api_key:
    secure: Q9v7Huzgx+vJC3E8oGhw/mART6brch/Dg+OIJLCo2YCdexCBCMb0/8Nay/Ldq07o
  skip_symbols: true
  artifact: 'C:\projects\obsidian\Obsidian.API\bin\Debug\Obsidian.API.{version}.nupkg'
  on:
    branch: master