# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: UseDotNet@2
#  displayName: 'Install .NET 5 SDK'
#  inputs:
#    version: 5.0.x
#    performMultiLevelLookup: true
#    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Obsidian'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet packages'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet packages to feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a98a2150-6b20-4ea2-aa86-771dc5468436/3c3a54df-2e6d-495c-ac75-1a7dbea7e928'