name: .NET Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Obsidian-Nightly-Build
        path: /home/runner/work/Obsidian/Obsidian/Obsidian/bin/Debug/net5.0/
